### Julia - Introduction

#### Comments

In [1]:
# This is a comment

#=
This is a multiline comment
=#

#### Strings

In [2]:
# Strings are stored in double or triple quotes

a = "hello"
b = """hellloooo""" 

"hellloooo"

In [3]:
# Include quotes in string

println("""Print something "with" quotes""")

Print something "with" quotes


In [4]:
# Concatenate strings

"Hello" * ", " * "World!"

"Hello, World!"

In [5]:
# Another way to concatenate

string("Hello, ", "dudes", " and ", "dudettes!") 

"Hello, dudes and dudettes!"

In [6]:
# Lexicograph comparison 

"hello" < "hellloooo"

false

In [7]:
# Indexing starts at 1!

println(a[0])

BoundsError: BoundsError: attempt to access String
  at index [0]

In [8]:
println(a[1])
println(length(a))

h
5


In [9]:
#Unlike in Python, indexing strings in Julia returns chars

"Hello"[3]

'l': ASCII/Unicode U+006c (category Ll: Letter, lowercase)

In [10]:
# Accessing the last character

a[end] 

'o': ASCII/Unicode U+006f (category Ll: Letter, lowercase)

In [11]:
findfirst(isequal('l'), a)

3

In [12]:
occursin("o", "Xylophon")

true

In [13]:
# Parts of string

a[2:4]

"ell"

In [14]:
# Display the type of variable
typeof(a)

String

#### Data Structures

Tuples

In [15]:
mytuple = ("item1", "item2", "item3")

("item1", "item2", "item3")

In [16]:
mytuple[1]

"item1"

In [17]:
# Tuples are immutable
mytuple[1] = "item4"

MethodError: MethodError: no method matching setindex!(::Tuple{String,String,String}, ::String, ::Int64)

In [18]:
mynamedtuple = (bird = "penguins", mammal = "cats", marsupial = "sugargliders")

(bird = "penguins", mammal = "cats", marsupial = "sugargliders")

In [19]:
mynamedtuple[1]

"penguins"

In [20]:
# Access values bu their name
mynamedtuple.bird

"penguins"

Dictionaries

In [21]:
# Create dictionary using the Dict() function

D = Dict("Maggie" => "Learning Julia", "Maggie's dog" => "Sleeping")

Dict{String,String} with 2 entries:
  "Maggie's dog" => "Sleeping"
  "Maggie"       => "Learning Julia"

In [22]:
# Access the elements of a dictionary

D["Maggie"]

"Learning Julia"

In [23]:
# Count elements of the dictionary

D.count 

2

In [24]:
# Add elements to dictionary

D["Bob"] = "Killing people in Twin Peaks"

"Killing people in Twin Peaks"

In [25]:
D

Dict{String,String} with 3 entries:
  "Maggie's dog" => "Sleeping"
  "Bob"          => "Killing people in Twin Peaks"
  "Maggie"       => "Learning Julia"

In [26]:
# Delete dictionary items

pop!(D, "Bob")

"Killing people in Twin Peaks"

In [27]:
# Dictioanries are unordered

D[1]

KeyError: KeyError: key 1 not found

Arrays

In [28]:
fibonacci = [1, 1, 2, 3, 5, 8, 13]

7-element Array{Int64,1}:
  1
  1
  2
  3
  5
  8
 13

In [29]:
fibonacci[3]

2

In [30]:
# Change items in array

fibonacci[3] = 888

888

In [31]:
# Add elements 

push!(fibonacci, 21)

8-element Array{Int64,1}:
   1
   1
 888
   3
   5
   8
  13
  21

In [32]:
# Arrays of arrays

numbers = [[1, 2, 3], [4, 5], [6, 7, 8, 9]]

3-element Array{Array{Int64,1},1}:
 [1, 2, 3]   
 [4, 5]      
 [6, 7, 8, 9]

In [33]:
# Copy arrays can cause issues

somenumbers = fibonacci
somenumbers[1] = 404
fibonacci

8-element Array{Int64,1}:
 404
   1
 888
   3
   5
   8
  13
  21

In [34]:
# First, restore fibonacci

fibonacci[1] = 1
fibonacci[3] = 2

2

In [35]:
# The correct way to copy

somemorenumbers = copy(fibonacci)
somemorenumbers[1] = 404
fibonacci

8-element Array{Int64,1}:
  1
  1
  2
  3
  5
  8
 13
 21

In [36]:
v = [3, 5, 2]

3-element Array{Int64,1}:
 3
 5
 2

In [37]:
sort(v) # sorts output

3-element Array{Int64,1}:
 2
 3
 5

In [38]:
sort!(v) # sorts in array

3-element Array{Int64,1}:
 2
 3
 5

##### Loops and conditional statements

In [39]:
# While
n = 0
while n < 10
    n += 1
    println(n)
end
n

1
2
3
4
5
6
7
8
9
10


10

In [40]:
# For
for n in 1:10
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [41]:
m, n = 5, 5
C = [i + j for i in 1:m, j in 1:n]

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [42]:
x = 6
y = 2

(x > y) ? x : y

6

In [43]:
(x > 0) && error("x cannot be greater than 0")

ErrorException: x cannot be greater than 0

In [44]:
(x < 0) || println("hi")

hi


#### Functions

In [45]:
# Declare function

function f(x)
    x*5
end

f (generic function with 1 method)

In [46]:
# Call function
f(6)

30

In [47]:
f2(x) = x^2 # Another way to declare on a single line

f2 (generic function with 1 method)

In [48]:
A = rand(3, 3)
A

3×3 Array{Float64,2}:
 0.0996638  0.877893  0.226465
 0.930375   0.706997  0.497657
 0.627206   0.936169  0.27587 

In [49]:
# Functions in Julia work on any input that makes sence
f2(A)

3×3 Array{Float64,2}:
 0.968743  0.920171  0.521935
 1.06263   1.78251   0.699828
 1.10653   1.47075   0.684035

In [50]:
broadcast(f2, [1, 2, 3])

3-element Array{Int64,1}:
 1
 4
 9

In [51]:
f2.([1, 2, 3])

3-element Array{Int64,1}:
 1
 4
 9

In [52]:
f2([1, 2, 3]) # because you cannot square a vector, only it's elements

MethodError: MethodError: no method matching ^(::Array{Int64,1}, ::Int64)
Closest candidates are:
  ^(!Matched::Float16, ::Integer) at math.jl:862
  ^(!Matched::Regex, ::Integer) at regex.jl:712
  ^(!Matched::Missing, ::Integer) at missing.jl:151
  ...

#### Some vector/matrix operations

In [53]:
A = [5, 10, 15] # this is a row vector

3-element Array{Int64,1}:
  5
 10
 15

In [54]:
A[1] # 1-indexed

5

In [55]:
A=[5;10;15] #column vector. semi-colon is used  to change row

3-element Array{Int64,1}:
  5
 10
 15

In [56]:
A[1] = 199
A

3-element Array{Int64,1}:
 199
  10
  15

In [57]:
M = [1 2 3;4 5 6;7 8 9] # matrixb

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [58]:
M[1,2] # access elements of the matrix

2

In [59]:
M' # transpose quickly 

3×3 LinearAlgebra.Adjoint{Int64,Array{Int64,2}}:
 1  4  7
 2  5  8
 3  6  9

In [60]:
inv(M)

LinearAlgebra.SingularException: LinearAlgebra.SingularException(3)

#### Compare Julia to Python

Consider the  **sum** function `sum(a)`, which computes
$$
\mathrm{sum}(a) = \sum_{i=1}^n a_i,
$$
where $n$ is the length of `a`.

In [61]:
a = rand(10^7) # 1D vector of random numbers, uniform on [0,1)

10000000-element Array{Float64,1}:
 0.8253995733359463    
 0.10839409999557414   
 0.9259054474632396    
 0.09497386076238112   
 0.9525544336220497    
 0.9657938125028376    
 0.6832491569982506    
 0.0803997150619844    
 0.2383058682998267    
 0.00032109533704138826
 0.3215791511749331    
 0.835894191386892     
 0.983055270342232     
 ⋮                     
 0.5099419347514422    
 0.19391371312934425   
 0.7470808729932994    
 0.11384746010735713   
 0.9256037085433781    
 0.9311837728190622    
 0.17219456571683667   
 0.7777739275798223    
 0.45738811014057545   
 0.4828592947298953    
 0.33047439345059515   
 0.381609626251626     

In [62]:
using Pkg
Pkg.add("BenchmarkTools")

  Updating registry at `C:\Users\m_b\.julia\registries\General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
Fetching: [========================================>]  100.0 %.0 %Fetching: [===>                                     ]  5.9 % [=====>                                   ]  11.5 %=======>                                 ]  16.9 % [==========>                              ]  24.3 %.9 % [===============>                         ]  35.0 %41.7 %]  48.8 % %                ]  59.8 % % [=============================>           ]  71.6 % [===============================>         ]  77.2 % [=================================>       ]  80.4 %Fetching: [===================================>     ]  85.5 %]  91.2 % ]  95.8 %========================================>]  99.8 % Resolving package versions...
 Installed GeometryTypes ── v0.7.9
 Installed DataStructures ─ v0.17.10
  Updating `C:\Users\m_b\.julia\environments\v1.3\Project.toml`
 [no changes]
  Updating `C:\Users

In [63]:
using BenchmarkTools

Hand-written python

In [64]:
using PyCall

┌ Info: Precompiling PyCall [438e738f-606a-5dbb-bf0a-cddfbfd45ab0]
└ @ Base loading.jl:1273


In [65]:
# Python code
py"""
def py_sum(A):
    s = 0.0
    for a in A:
        s += a
    return s
"""

sum_py = py"py_sum"

PyObject <function py_sum at 0x00000000307F2CA8>

In [66]:
py_hand = @benchmark $sum_py($a)

BenchmarkTools.Trial: 
  memory estimate:  352 bytes
  allocs estimate:  7
  --------------
  minimum time:     1.628 s (0.00% GC)
  median time:      1.685 s (0.00% GC)
  mean time:        1.674 s (0.00% GC)
  maximum time:     1.699 s (0.00% GC)
  --------------
  samples:          4
  evals/sample:     1

In [67]:
sum_py(a)

5.000376448165394e6

In [68]:
sum_py(a) ≈ sum(a)

true

In [69]:
d = Dict() 

Dict{Any,Any} with 0 entries

In [70]:
d["Python hand-written"] = minimum(py_hand.times) / 1e6
d

Dict{Any,Any} with 1 entry:
  "Python hand-written" => 1627.85

Build-in Python

In [73]:
# get the Python built-in "sum" function:
pysum = pybuiltin("sum")

PyObject <built-in function sum>

In [74]:
pysum(a)

5.000376448165394e6

In [75]:
pysum(a) ≈ sum(a)

true

In [76]:
py_list_bench = @benchmark $pysum($a)

BenchmarkTools.Trial: 
  memory estimate:  352 bytes
  allocs estimate:  7
  --------------
  minimum time:     1.269 s (0.00% GC)
  median time:      1.273 s (0.00% GC)
  mean time:        1.274 s (0.00% GC)
  maximum time:     1.282 s (0.00% GC)
  --------------
  samples:          4
  evals/sample:     1

In [77]:
d["Python built-in"] = minimum(py_list_bench.times) / 1e6
d

Dict{Any,Any} with 2 entries:
  "Python hand-written" => 1627.85
  "Python built-in"     => 1269.39

Numpy 

In [78]:
using Conda
Conda.add("numpy")

┌ Info: Running `conda install -y numpy` in root environment
└ @ Conda C:\Users\m_b\.julia\packages\Conda\3rPhK\src\Conda.jl:113


Solving environment: ...working... done

# All requested packages already installed.



In [79]:
numpy_sum = pyimport("numpy")["sum"]

py_numpy_bench = @benchmark $numpy_sum($a)

┌ Warning: `getindex(o::PyObject, s::AbstractString)` is deprecated in favor of dot overloading (`getproperty`) so elements should now be accessed as e.g. `o."s"` instead of `o["s"]`.
│   caller = top-level scope at In[79]:1
└ @ Core In[79]:1


BenchmarkTools.Trial: 
  memory estimate:  352 bytes
  allocs estimate:  7
  --------------
  minimum time:     9.208 ms (0.00% GC)
  median time:      11.148 ms (0.00% GC)
  mean time:        11.303 ms (0.00% GC)
  maximum time:     15.255 ms (0.00% GC)
  --------------
  samples:          442
  evals/sample:     1

In [80]:
numpy_sum(a)

5.000376448164994e6

In [81]:
numpy_sum(a) ≈ sum(a)

true

In [82]:
d["Python numpy"] = minimum(py_numpy_bench.times) / 1e6
d

Dict{Any,Any} with 3 entries:
  "Python numpy"        => 9.2083
  "Python hand-written" => 1627.85
  "Python built-in"     => 1269.39

Built-in Julia

In [83]:
@which sum(a)

sum(a::AbstractArray) in Base at reducedim.jl:652

In [84]:
j_bench = @benchmark sum($a)

BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     3.694 ms (0.00% GC)
  median time:      4.066 ms (0.00% GC)
  mean time:        4.113 ms (0.00% GC)
  maximum time:     5.803 ms (0.00% GC)
  --------------
  samples:          1214
  evals/sample:     1

In [85]:
d["Julia built-in"] = minimum(j_bench.times) / 1e6
d

Dict{Any,Any} with 4 entries:
  "Python numpy"        => 9.2083
  "Python hand-written" => 1627.85
  "Python built-in"     => 1269.39
  "Julia built-in"      => 3.694

Hand-written Julia

In [86]:
function mysum(A)
    s = 0.0 # s = zero(eltype(a))
    for a in A
        s += a
    end
    s
end

mysum (generic function with 1 method)

In [87]:
j_bench_hand = @benchmark mysum($a)

BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     10.317 ms (0.00% GC)
  median time:      10.905 ms (0.00% GC)
  mean time:        10.824 ms (0.00% GC)
  maximum time:     11.225 ms (0.00% GC)
  --------------
  samples:          462
  evals/sample:     1

In [88]:
d["Julia hand-written"] = minimum(j_bench_hand.times) / 1e6
d

Dict{Any,Any} with 5 entries:
  "Python numpy"        => 9.2083
  "Julia hand-written"  => 10.3169
  "Python hand-written" => 1627.85
  "Python built-in"     => 1269.39
  "Julia built-in"      => 3.694

Julia hand-written with smd.

In [89]:
function mysum_simd(A)
    s = 0.0 # s = zero(eltype(A))
    @simd for a in A
        s += a
    end
    s
end

mysum_simd (generic function with 1 method)

In [90]:
j_bench_hand_simd = @benchmark mysum_simd($a)

BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     3.628 ms (0.00% GC)
  median time:      4.388 ms (0.00% GC)
  mean time:        4.377 ms (0.00% GC)
  maximum time:     6.371 ms (0.00% GC)
  --------------
  samples:          1140
  evals/sample:     1

In [91]:
mysum_simd(a)

5.000376448165009e6

In [92]:
d["Julia hand-written simd"] = minimum(j_bench_hand_simd.times) / 1e6
d

Dict{Any,Any} with 6 entries:
  "Julia hand-written simd" => 3.6281
  "Python numpy"            => 9.2083
  "Julia hand-written"      => 10.3169
  "Python hand-written"     => 1627.85
  "Python built-in"         => 1269.39
  "Julia built-in"          => 3.694

In [93]:
# Summary

for (key, value) in sort(collect(d), by=last)
    println(rpad(key, 25, "."), lpad(round(value; digits=1), 6, "."))
end

Julia hand-written simd.....3.6
Julia built-in..............3.7
Python numpy................9.2
Julia hand-written.........10.3
Python built-in..........1269.4
Python hand-written......1627.9
